### ISSUE TITLE
React component <CssBoundary> throws `NotSupportedError` when in <StrictMode>

### ISSUE THREAD

**Issue by deltaidea** [alex-vukov/css-boundary#3]
Thank you for working on this useful little library! I've ran into the following issue:

## Expectations

This code should successfully render "Hello world", same as without `<StrictMode>`:

```jsx
<React.StrictMode>
  <CssBoundary>Hello world</CssBoundary>
</React.StrictMode>
```

## Actual behavior

In development builds, `<StrictMode>` calls `effect -> cleanup -> effect` [to verify that effects are cleaned up properly](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development).

In the case of `<CssBoundary>`, this leads to `Uncaught DOMException: Operation is not supported`. Offending line:

https://github.com/alex-vukov/css-boundary/blob/4705fb46217cdf4ff48fc6aaaa7b789796969a1e/src/styleLoader.ts#L12

This is because calling `Element.attachShadow()` on the same element twice is not allowed.

Specifically, `<CssBoundary>` creates a shadow root and never re-mounts a new one, even during or after the effect cleanup:

https://github.com/alex-vukov/css-boundary/blob/4705fb46217cdf4ff48fc6aaaa7b789796969a1e/src/CssBoundary.tsx#L9-L15

`deleteShadowInstance()` only removes the `<div>` from the library's internal lookup table, but doesn't clean up the `<div>` itself.

I'm guessing the same issue can be reproduced even without `StrictMode`, simply by changing `props.init` after mounting.

## Environment

```json5
"dependencies": {
  "css-boundary": "1.0.2",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  // More stuff...
},
```

Tested in Firefox but I'm sure it's the same in Chrome.

## Possible solution

A shadow root [can only be attached but not detached](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow). So the next best option is to throw away the host `<div>` itself and mount a new one every time `props.init` changes.

I ended up implementing a version of this component myself, maybe it will be useful for reference:

```tsx
import * as React from "react";
import * as ReactDOM from "react-dom";

import { PropsWithChildren, useEffect, useRef, useState } from "react";
import { createShadowInstance, deleteShadowInstance } from "css-boundary/dist/styleLoader";

export const CssBoundary: React.FC<PropsWithChildren<{ init?: ShadowRootInit }>> = ({ children, init }) => {
  // Wait for a `<div>` to be rendered, then delegate to `createShadowInstance()`.
  const divRef = useRef<HTMLDivElement>(null);

  // Re-mount the `<div>` when props change. We can't un-attach shadow DOM, so we have to create a new `<div>`.
  const [divId, setDivId] = useState<string>();
  const [isReadyToAttachShadowRoot, setReady] = useState(false);
  const [shadowRoot, setShadowRoot] = useState<ShadowRoot>();

  // Make a fresh `<div>` by changing its ID which is also used as its `key`.
  // React treats elements with different `key`s as unrelated and mounts a new `<div>`.
  useEffect(() => {
    setDivId(`${Date.now() + Math.random()}`);
    setReady(false);
  }, [init]);

  // Set a (otherwise meaningless) bit of state to force re-render when the ref is ready.
  useEffect(() => {
    setReady(!!divRef?.current);
  }, [!!divRef?.current]);

  // Delegate to `createShadowInstance()` whenever a fresh `<div>` is ready after a change in props.
  useEffect(() => {
    if (divId && isReadyToAttachShadowRoot) {
      // A fresh `<div>` is ready for use.
      setShadowRoot(createShadowInstance(divId, init));
      return () => {
        // This is in a closure scope, so this removes the old ID from internal library state
        // immediately before this effect runs again and sets up a new shadow root.
        deleteShadowInstance(divId);
      };
    } else {
      return () => {};
    }
  }, [isReadyToAttachShadowRoot]);

  return (
    <div key={divId} id={divId} ref={divRef}>
      {divId && shadowRoot && ReactDOM.createPortal(children, shadowRoot)}
    </div>
  );
};
```

**Comment by alex-vukov** [comment]
Hi @deltaidea,
Thank you very much for using my library and for providing such a detailed explanation of the issue, and for even suggesting a working solution! Let me run some tests locally and I will create a PR with the fix. I will ping you when I have it fixed!

**Comment by alex-vukov** [comment]
Hi @deltaidea,
I have released a fix and you can get it with css-boundary version 1.0.3. I had the issue reproduced and tested it in this repo https://github.com/alex-vukov/css-boundary-example

Thank you :)
